obj-$(CONFIG_FOTA_DM_BACKEND_HAWKBIT) += hawkbit.o
obj-$(CONFIG_FOTA_DM_BACKEND_HAWKBIT) += jsmn.o
obj-$(CONFIG_FOTA_DM_BACKEND_HAWKBIT) += flash_block.o
obj-$(CONFIG_FOTA_CONSOLE_SHELL) += fota_shell.o
obj-y += mcuboot.o
obj-y += product_id.o
obj-$(CONFIG_NET_TCP) += tcp.o
obj-$(CONFIG_FOTA_BLUEMIX) += bluemix.o
